{"uuid": "afe8b824-f2d7-4072-9b64-8485de1d8825", "children": ["e4c2b6cc-d1f3-43ea-a679-bafbf7faff51"], "befores": [{"name": "setup_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; Message: Unsuccessful command executed: C:\\Users\\annguyenq\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nThe chromedriver version cannot be discovered\n; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"C:\\Users\\annguyenq\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\Desktop\\ATE-AutomationFW-Selenium-Non_BDD-Python-main\\DemoQABookStore\\testcases\\ui\\conftest.py\", line 22, in setup_driver\n    DriverManager.init_driver(pytest.driver_conf)\n  File \"C:\\Users\\annguyenq\\Desktop\\ATE-AutomationFW-Selenium-Non_BDD-Python-main\\DemoQABookStore\\core\\driver\\driver_manager.py\", line 16, in init_driver\n    cls.driver = driver_mapping[config.driver].create_driver(config)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\Desktop\\ATE-AutomationFW-Selenium-Non_BDD-Python-main\\DemoQABookStore\\core\\driver\\driver_types\\chrome_driver.py\", line 16, in create_driver\n    self._driver = webdriver.Chrome(service=Service(), options=options)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 47, in __init__\n    self.service.path = DriverFinder.get_path(self.service, self.options)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\annguyenq\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 44, in get_path\n    raise NoSuchDriverException(f\"Unable to obtain {service.path} using Selenium Manager; {err}\")\n"}, "start": 1702368261597, "stop": 1702368263716}], "start": 1702368261597, "stop": 1702368263726}