{"name": "Test login with invalid accounts", "status": "passed", "parameters": [{"name": "account", "value": "<data_object.account.Account object at 0x000001F768252E10>"}], "start": 1702455157290, "stop": 1702455158918, "uuid": "3b6d2e31-7c05-4d41-a91b-bafdbb075136", "historyId": "652ebd9a5b82e5fafa1fb51d8900d527", "testCaseId": "1b1f20a980acb2adddf0d9d9639eb7fe", "fullName": "testcases.ui.test_login#test_login_unsuccessfully_with_valid_account", "labels": [{"name": "suite", "value": "Test Login"}, {"name": "parentSuite", "value": "UI Test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "VNNOT02222"}, {"name": "thread", "value": "3328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.ui.test_login"}]}