{"name": "Test login with invalid accounts", "status": "passed", "parameters": [{"name": "account", "value": "<data_object.account.Account object at 0x000001F768252DE0>"}], "start": 1702455099177, "stop": 1702455100819, "uuid": "b19f40ce-a431-4df6-abca-6a8be1f38024", "historyId": "385d39d62c4372912deb98e5861334cd", "testCaseId": "1b1f20a980acb2adddf0d9d9639eb7fe", "fullName": "testcases.ui.test_login#test_login_unsuccessfully_with_valid_account", "labels": [{"name": "suite", "value": "Test Login"}, {"name": "parentSuite", "value": "UI Test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "VNNOT02222"}, {"name": "thread", "value": "3328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.ui.test_login"}]}